### ISSUE TITLE
Questions around <http:response/>

### ISSUE THREAD

**Issue by ChristianGruen** [exquery/exquery#10]
Hi Adam, I noticed that the schema of the `<http:response/>` element is different to the one proposed in the EXPath HTTP specification:

  http://www.expath.org/spec/http-client#d2e491

For example, the `message` attribute name is called `reason` in the XMLPrague proposal for RESTXQ. Next, there is no `<http:body/>` element. Instead, all results are returned as additional items.. which is of course reasonable if we plan to also return non-textual data.

**Comment by adamretter** [comment]
Hi Christian, terribly sorry. For some reason I completely missed this. Is it still something you need an answer on?

**Comment by ChristianGruen** [comment]
Hi Adam, I stumbled upon this issue, because @dizzzz changed a little example in our documentation (http://docs.basex.org/index.php?title=RESTXQ&action=historysubmit&diff=13833&oldid=13809 …hi Dannes!).

In the specifications…

* http://expath.org/spec/http-client#d2e491
* http://exquery.github.io/exquery/exquery-restxq-specification/restxq-1.0-specification.html#response-format

…the response attribute is called `message`, so maybe we should change this back from `reason` to `message`?

The current version of the BaseX RESTXQ implementation provides support for both attributes.

**Comment by ChristianGruen** [comment]
Hi Dannes, hi Adam, do you have any opinion on this? Thanks in advance!

**Comment by dizzzz** [comment]
I have no opinion here, as long it works cross-vendor :)

**Comment by dizzzz** [comment]
suggested fix in PR #35

**Comment by ChristianGruen** [comment]
Thanks for your feedback, Dannes!

**Comment by dizzzz** [comment]
We have to undo the wiki change :)

**Comment by ChristianGruen** [comment]
Just done ;)
