### ISSUE TITLE
Feature Proposal: Include PATCH method

### ISSUE THREAD

**Issue by dariok** [exquery/exquery#70]
(this has also been mentioned in a comment to #22)

The PATCH method as defined in RFC5789 is especially useful in an XML database environment. I think it should be included in the available methods.

While in baseX allows the use of custom verbs in `%rest:method`, eXist does not – which means that PATCH requests are not possible in eXist.
With the PATCH method established in said RFC, I think it would be a good idea to include it so that there can be a standard way of RESTful patching.

**Comment by adamretter** [comment]
This has been added in #88 as `%rest:PATCH`
